---
# This is a sample database file for the ActiveRecord ORM

:development: &defaults
  :adapter: mysql
  :database: download_kg
  :host: 127.0.0.1
  :username: root
  :password: qweasd

:test:
  <<: *defaults
  :database: test.sqlite

:production:
  <<: *defaults
  :database: production.sqlite
  
:rake:
  <<: *defaults